version: "3.8"
services:
#  db:
#    image: mysql
#    command: --init-file /data/application/init.sql
#    volumes:
#      - ./init.sql:/data/application/init.sql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#      timeout: 20s
#      retries: 10

#  activemq-artemis:
#    image: vromero/activemq-artemis:2.9.0-alpine
#    ports:
#      - "8161:8161"
#      - "61616:61616"
#    environment:
#      ARTEMIS_USERNAME: "quarkus"
#      ARTEMIS_PASSWORD: "quarkus"

  orders:
    build:
      context: orders
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy

  customers:
    build:
      context: customers
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8080"
#    depends_on:
#      db:
#        condition: service_healthy

  finances:
    build:
      context: finance
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8082:8080"

  baristas:
    build:
      context: barista
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8083:8080"