version: "3.8"
services:
  orders:
    build:
      context: orders
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"

  customers:
    build:
      context: customers
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8080"

  finances:
    build:
      context: finance
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8082:8080"

  baristas:
    build:
      context: barista
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8083:8080"

  orders-history:
    build:
      context: orders-history
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8084:8080"