version: "3.8"
services:
#  db:
#    image: mysql
#    command: --init-file /data/application/init.sql
#    volumes:
#      - ./init.sql:/data/application/init.sql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#      timeout: 20s
#      retries: 10

#  activemq-artemis:
#    image: vromero/activemq-artemis:2.9.0-alpine
#    ports:
#      - "8161:8161"
#      - "61616:61616"
#    environment:
#      ARTEMIS_USERNAME: "quarkus"
#      ARTEMIS_PASSWORD: "quarkus"

  orders:
    build:
      context: orders
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy

  customers:
    build:
      context: customers
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8080"
#    depends_on:
#      db:
#        condition: service_healthy

  finances:
    build:
      context: finance
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8082:8080"

  baristas:
    build:
      context: barista
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8083:8080"

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    command: [ "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411" ]
    ports:
      - "14269"
      - "14268:14268"
      - "14250"
      - "9411:9411"
    restart: on-failure
    depends_on:
      - cassandra-schema

  jaeger-query:
    image: jaegertracing/jaeger-query
    command: [ "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra" ]
    ports:
      - "16686:16686"
      - "16687"
    restart: on-failure
    depends_on:
      - cassandra-schema
  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command: [ "--reporter.grpc.host-port=jaeger-collector:14250" ]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
    depends_on:
      - jaeger-collector
  cassandra:
    image: cassandra:3.9

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema
    depends_on:
      - cassandra