CREATE DATABASE IF NOT EXISTS keycloak;
CREATE DATABASE IF NOT EXISTS orders_service;
CREATE DATABASE IF NOT EXISTS finances_service;
CREATE DATABASE IF NOT EXISTS baristas_service;
CREATE DATABASE IF NOT EXISTS customers_service;