apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-set
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      containers:
        - name: mongodb
          image: mvertes/alpine-mongo
          imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb